/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplianceGuideRouteImport } from './routes/appliance-guide'
import { Route as HouseRulesRouteImport } from './routes/house-rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplianceGuideRoute = ApplianceGuideRouteImport.update({
  id: '/appliance-guide',
  path: '/appliance-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRulesRoute = HouseRulesRouteImport.update({
  id: '/house-rules',
  path: '/house-rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appliance-guide': typeof ApplianceGuideRoute
  '/house-rules': typeof HouseRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appliance-guide': typeof ApplianceGuideRoute
  '/house-rules': typeof HouseRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appliance-guide': typeof ApplianceGuideRoute
  '/house-rules': typeof HouseRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appliance-guide' | '/house-rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appliance-guide' | '/house-rules'
  id: '__root__' | '/' | '/appliance-guide' | '/house-rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplianceGuideRoute: typeof ApplianceGuideRoute
  HouseRulesRoute: typeof HouseRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appliance-guide': {
      id: '/appliance-guide'
      path: '/appliance-guide'
      fullPath: '/appliance-guide'
      preLoaderRoute: typeof ApplianceGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-rules': {
      id: '/house-rules'
      path: '/house-rules'
      fullPath: '/house-rules'
      preLoaderRoute: typeof HouseRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplianceGuideRoute: ApplianceGuideRoute,
  HouseRulesRoute: HouseRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
